### ISSUE TITLE
Concerning sys-ftpd and layeredFS

### ISSUE THREAD

**Issue by Favna** [Random0666/SwitchPresence#3]
Since the readme states `not confirmed yet` I would like to share some of my own results. These are based on using tumGER's Latest SD Files Hekate configurations.

- FTP + CFW (no LayeredFS) => Adding SwitchPresence works
- LayeredFS (no FTP) => Stuck on Nintendo Switch boot logo
- FTP + LayeredFS => Stuck on Nintendo Switch boot logo

TL;DR: Works with Sys-FTPD, doesn't work with LayeredFS

**Comment by Random0666** [comment]
Thanks a lot for your feedback, I'll update the readme and eventually fixe the issue later if I have time.

**Comment by Random0666** [comment]
I just fixed the issue with at least LayeredFS and sys-ftpd. It'll theoretically work with any other sysmodule as long as there is memory left.

**Comment by Favna** [comment]
Very nice. I'll be here to check it out as soon as I can.

**Comment by Favna** [comment]
I was just looking at things and just for clarifications are all these changes included in the v1.0.3 release? Since the releases page says `3 commits to master since this release` with among them being you updating the readme and titleid.

I personally never bothered setting up NX devkit so it would be nice to get a build version if not.

**Comment by Random0666** [comment]
All changes were indeed included in v1.0.3 release, the problem was just me trying to go fast without really checking everything. It should be fixed now
