### ISSUE TITLE
Different client id's for different games

### ISSUE THREAD

**Issue by Karthik99999** [Random0666/SwitchPresence#4]
Is there a way you could implement this? I really don't like how it can only use one, leaving it at "Nintendo Switch" as the game name. I'd rather have it say "Mario Kart 8 Deluxe" Or "BOTW" or something when playing that respective game.

**Comment by SunTheCourier** [comment]
You can already do this? change the config.txt

**Comment by Karthik99999** [comment]
I know that. But I want something where it uses a different client I’d for each game without me having to go into the config every time I want to change the display name

**Comment by SunTheCourier** [comment]
ah

**Comment by Random0666** [comment]
I don't really get it since the clients only contain the picture and the title id of the game

**Comment by SunTheCourier** [comment]
The name of the app is the display *Playing* [App name]
